// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxtjs/google-fonts"],
  googleFonts: {
    families: {
      Roboto: true,
      "Roboto Slab": true,
      "Roboto Mono": true,
      "Open Sans": true,
      Lato: true,
      Montserrat: true,
      Raleway: true,
      Poppins: true,
      Merriweather: true,
      Oswald: true,
      "PT Sans": true,
      "Playfair Display": true,
      Playfair: true,
      "Source Code Pro": true,
      "Noto Sans": true,
      Inter: true,
      Nunito: true,
      Alegreya: true,
      Rubik: true,
      Ubuntu: true,
      "Fira Sans": true,
      Aleo: true,
      "Archivo Narrow": true,
      Barlow: true,
      "Courier Prime": true,
      Lora: true,
      "Slabo 13px": true,
      "Slabo 27px": true,
      "Noto Serif": true,
      "PT Serif": true,
      "Libre Baskerville": true,
      Vollkorn: true,
      "Fira Sans Condensed": true,
      "Proza Libre": true,
      "Work Sans": true,
      "Bebas Neue": true,
      Lobster: true,
      Comfortaa: true,
      "Abril Fatface": true,
      "Alfa Slab One": true,
      Cormorant: true,
      Italiana: true,
      "Antic Didone": true,
      Cinzel: true,
      "Dancing Script": true,
      Pacifico: true,
      "Shadows Into Light": true,
      "Indie Flower": true,
      Caveat: true,
      "Homemade Apple": true,
      "League Script": true,
      "Cedarville Cursive": true,
      "Berkshire Swash": true,
      "La Belle Aurore": true,
      Inconsolata: true,
      "IBM Plex Mono": true,
      "Noto Sans Mono": true,
      "Anonymous Pro": true,
      "Azeret Mono": true,
      "JetBrains Mono": true,
    },
  },
});
